const sequelize = require('./sequelize');
const faker = require('faker/locale/pl');

const Owner = require('../../model/sequelize/Owner');
const Vehicle = require('../../model/sequelize/Vehicle_');
const OwnerVehicle = require('../../model/sequelize/OwnerVehicle');
const Announcement = require('../../model/sequelize/Announcement');

module.exports = () => {
    Owner.hasMany(OwnerVehicle, {as: 'ownerVehicles', foreignKey: {name: 'owner_id', allowNull: false}, constraints: true, onDelete: 'CASCADE'});
    OwnerVehicle.belongsTo(Owner, {as: 'owner', foreignKey: {name: 'owner_id', allowNull: false} } );
    Vehicle.hasMany(OwnerVehicle, {as: 'ownerVehicles', foreignKey: {name: 'vehicle_id', allowNull: false}, constraints: true, onDelete: 'CASCADE'});
    OwnerVehicle.belongsTo(Vehicle, {as: 'vehicle', foreignKey: {name: 'vehicle_id', allowNull: false} });

    let allOwners, allVehicles;
    let registrations;
    return sequelize
        .sync({force: true})
        .then( () => {
            return Owner.findAll();
        })
        .then(owners => {
            if( !owners || owners.length === 0 ) {
                return Owner.bulkCreate([{
                    "id": 1,
                    "firstName": "Lew",
                    "lastName": "Plowright",
                    "email": "lplowright0@youku.com",
                    "phoneNumber": "6895595807"
                }, {
                    "id": 2,
                    "firstName": "Shandeigh",
                    "lastName": "Robbins",
                    "email": "srobbins1@zimbio.com",
                    "phoneNumber": "9379136704"
                }, {
                    "id": 3,
                    "firstName": "Elena",
                    "lastName": "Mycroft",
                    "email": "emycroft2@mayoclinic.com",
                    "phoneNumber": "5544290679"
                }, {
                    "id": 4,
                    "firstName": "Eb",
                    "lastName": "Sutch",
                    "email": "esutch3@webmd.com",
                    "phoneNumber": "3183413073"
                }, {
                    "id": 5,
                    "firstName": "Niki",
                    "lastName": "Blackly",
                    "email": "nblackly4@cnbc.com",
                    "phoneNumber": "8967016503"
                }, {
                    "id": 6,
                    "firstName": "Fayre",
                    "lastName": "Rubinsztein",
                    "email": "frubinsztein5@blogradio.com",
                    "phoneNumber": "3475963290"
                }, {
                    "id": 7,
                    "firstName": "Dulciana",
                    "lastName": "Nicholls",
                    "email": "dnicholls6@chron.com",
                    "phoneNumber": "5744670307"
                }, {
                    "id": 8,
                    "firstName": "Townie",
                    "lastName": "Meaddowcroft",
                    "email": "tmeaddowcroft7@wikipedia.org",
                    "phoneNumber": "5755396415"
                }, {
                    "id": 9,
                    "firstName": "Meggie",
                    "lastName": "Spere",
                    "email": "mspere8@joomla.org",
                    "phoneNumber": "4935524923"
                }, {
                    "id": 10,
                    "firstName": "Ursulina",
                    "lastName": "Jancic",
                    "email": "ujancic9@csmonitor.com",
                    "phoneNumber": "7017032516"
                }, {
                    "id": 11,
                    "firstName": "Traver",
                    "lastName": "Normandale",
                    "email": "tnormandalea@narod.ru",
                    "phoneNumber": "9508999080"
                }, {
                    "id": 12,
                    "firstName": "Georgia",
                    "lastName": "Behning",
                    "email": "gbehningb@yolasite.com",
                    "phoneNumber": "6599621336"
                }, {
                    "id": 13,
                    "firstName": "Maribelle",
                    "lastName": "Wolland",
                    "email": "mwollandc@paginegialle.it",
                    "phoneNumber": "2409471213"
                }, {
                    "id": 14,
                    "firstName": "Ilka",
                    "lastName": "Hawley",
                    "email": "ihawleyd@hostgator.com",
                    "phoneNumber": "3638750619"
                }, {
                    "id": 15,
                    "firstName": "Kayne",
                    "lastName": "Frigout",
                    "email": "kfrigoute@w3.org",
                    "phoneNumber": "7148014710"
                }, {
                    "id": 16,
                    "firstName": "Donnajean",
                    "lastName": "Fronek",
                    "email": "dfronekf@cloudflare.com",
                    "phoneNumber": "5859018664"
                }, {
                    "id": 17,
                    "firstName": "Virginie",
                    "lastName": "Heartfield",
                    "email": "vheartfieldg@ebay.com",
                    "phoneNumber": "5416930633"
                }, {
                    "id": 18,
                    "firstName": "Cointon",
                    "lastName": "Rengger",
                    "email": "crenggerh@yale.edu",
                    "phoneNumber": "2758117210"
                }, {
                    "id": 19,
                    "firstName": "Lottie",
                    "lastName": "Stovin",
                    "email": "lstovini@ucla.edu",
                    "phoneNumber": "2534896632"
                }, {
                    "id": 20,
                    "firstName": "Kynthia",
                    "lastName": "Cleugh",
                    "email": "kcleughj@last.fm",
                    "phoneNumber": "2336829046"
                }, {
                    "id": 21,
                    "firstName": "Lizzie",
                    "lastName": "Mont",
                    "email": "lmontk@hibu.com",
                    "phoneNumber": "2745442720"
                }, {
                    "id": 22,
                    "firstName": "Eden",
                    "lastName": "Blazey",
                    "email": "eblazeyl@unc.edu",
                    "phoneNumber": "3963617812"
                }, {
                    "id": 23,
                    "firstName": "Glenna",
                    "lastName": "Vickers",
                    "email": "gvickersm@squidoo.com",
                    "phoneNumber": "1835740131"
                }, {
                    "id": 24,
                    "firstName": "Cob",
                    "lastName": "Frears",
                    "email": "cfrearsn@dedecms.com",
                    "phoneNumber": "1073670979"
                }, {
                    "id": 25,
                    "firstName": "Calley",
                    "lastName": "Keyhoe",
                    "email": "ckeyhoeo@house.gov",
                    "phoneNumber": "3565589838"
                }, {
                    "id": 26,
                    "firstName": "Freddi",
                    "lastName": "Brosch",
                    "email": "fbroschp@github.com",
                    "phoneNumber": "3473400701"
                }, {
                    "id": 27,
                    "firstName": "Hughie",
                    "lastName": "Alexsandrev",
                    "email": "halexsandrevq@intel.com",
                    "phoneNumber": "6594541795"
                }, {
                    "id": 28,
                    "firstName": "Katherina",
                    "lastName": "Wallenger",
                    "email": "kwallengerr@mlb.com",
                    "phoneNumber": "4152915602"
                }, {
                    "id": 29,
                    "firstName": "Glynis",
                    "lastName": "Mushett",
                    "email": "gmushetts@amazon.de",
                    "phoneNumber": "8131534032"
                }, {
                    "id": 30,
                    "firstName": "Malcolm",
                    "lastName": "Broomhall",
                    "email": "mbroomhallt@topsy.com",
                    "phoneNumber": "7841496175"
                }, {
                    "id": 31,
                    "firstName": "Hamlin",
                    "lastName": "Giggs",
                    "email": "hgiggsu@tuttocitta.it",
                    "phoneNumber": "7092305239"
                }, {
                    "id": 32,
                    "firstName": "Pam",
                    "lastName": "McAline",
                    "email": "pmcalinev@seesaa.net",
                    "phoneNumber": "4939969090"
                }, {
                    "id": 33,
                    "firstName": "Nollie",
                    "lastName": "Mulheron",
                    "email": "nmulheronw@tamu.edu",
                    "phoneNumber": "2601256803"
                }, {
                    "id": 34,
                    "firstName": "Meredith",
                    "lastName": "Henriques",
                    "email": "mhenriquesx@list-manage.com",
                    "phoneNumber": "8992962031"
                }, {
                    "id": 35,
                    "firstName": "Justino",
                    "lastName": "Spirit",
                    "email": "jspirity@springer.com",
                    "phoneNumber": "7093466928"
                }, {
                    "id": 36,
                    "firstName": "Eli",
                    "lastName": "Ervin",
                    "email": "eervinz@tmall.com",
                    "phoneNumber": "1852622841"
                }, {
                    "id": 37,
                    "firstName": "Jay",
                    "lastName": "Coppledike",
                    "email": "jcoppledike10@t-online.de",
                    "phoneNumber": "4392826370"
                }, {
                    "id": 38,
                    "firstName": "Lyndsie",
                    "lastName": "Dunklee",
                    "email": "ldunklee11@theguardian.com",
                    "phoneNumber": "1918076004"
                }, {
                    "id": 39,
                    "firstName": "Bald",
                    "lastName": "Deery",
                    "email": "bdeery12@wikipedia.org",
                    "phoneNumber": "1398350683"
                }, {
                    "id": 40,
                    "firstName": "Ernestus",
                    "lastName": "Matfin",
                    "email": "ematfin13@about.me",
                    "phoneNumber": "5912674954"
                }, {
                    "id": 41,
                    "firstName": "Brantley",
                    "lastName": "Sparkwill",
                    "email": "bsparkwill14@storify.com",
                    "phoneNumber": "2076527781"
                }, {
                    "id": 42,
                    "firstName": "Shawna",
                    "lastName": "Christopherson",
                    "email": "schristopherson15@nih.gov",
                    "phoneNumber": "2935238591"
                }, {
                    "id": 43,
                    "firstName": "Christos",
                    "lastName": "Renowden",
                    "email": "crenowden16@plala.or.jp",
                    "phoneNumber": "7744803046"
                }, {
                    "id": 44,
                    "firstName": "Domeniga",
                    "lastName": "Hardwell",
                    "email": "dhardwell17@contact.com",
                    "phoneNumber": "8671834782"
                }, {
                    "id": 45,
                    "firstName": "Tana",
                    "lastName": "Maddick",
                    "email": "tmaddick18@com.com",
                    "phoneNumber": "8577298535"
                }, {
                    "id": 46,
                    "firstName": "Ki",
                    "lastName": "Earpe",
                    "email": "kearpe19@hp.com",
                    "phoneNumber": "5824348578"
                }, {
                    "id": 47,
                    "firstName": "Pepita",
                    "lastName": "Eccleston",
                    "email": "peccleston1a@parallels.com",
                    "phoneNumber": "2223250088"
                }, {
                    "id": 48,
                    "firstName": "Livvy",
                    "lastName": "Axtell",
                    "email": "laxtell1b@g.co",
                    "phoneNumber": "2546340160"
                }, {
                    "id": 49,
                    "firstName": "Ferris",
                    "lastName": "Tulley",
                    "email": "ftulley1c@samsung.com",
                    "phoneNumber": "9596979637"
                }, {
                    "id": 50,
                    "firstName": "Yolanthe",
                    "lastName": "Hampson",
                    "email": "yhampson1d@indiatimes.com",
                    "phoneNumber": "1345677419"
                }, {
                    "id": 51,
                    "firstName": "Hestia",
                    "lastName": "Rissom",
                    "email": "hrissom1e@japanpost.jp",
                    "phoneNumber": "4223674089"
                }, {
                    "id": 52,
                    "firstName": "Idaline",
                    "lastName": "Andrichuk",
                    "email": "iandrichuk1f@csmonitor.com",
                    "phoneNumber": "8431567165"
                }, {
                    "id": 53,
                    "firstName": "Phyllys",
                    "lastName": "Piken",
                    "email": "ppiken1g@naver.com",
                    "phoneNumber": "2659572064"
                }, {
                    "id": 54,
                    "firstName": "Harley",
                    "lastName": "Hamlet",
                    "email": "hhamlet1h@de.vu",
                    "phoneNumber": "5969209266"
                }, {
                    "id": 55,
                    "firstName": "Jeffie",
                    "lastName": "Ankrett",
                    "email": "jankrett1i@chicaibune.com",
                    "phoneNumber": "6632992058"
                }, {
                    "id": 56,
                    "firstName": "Elroy",
                    "lastName": "Fortescue",
                    "email": "efortescue1j@quantcast.com",
                    "phoneNumber": "6903326878"
                }, {
                    "id": 57,
                    "firstName": "Megan",
                    "lastName": "Redsull",
                    "email": "mredsull1k@chronoengine.com",
                    "phoneNumber": "8446629654"
                }, {
                    "id": 58,
                    "firstName": "Jyoti",
                    "lastName": "Gallamore",
                    "email": "jgallamore1l@constantcontact.com",
                    "phoneNumber": "9497033931"
                }, {
                    "id": 59,
                    "firstName": "Christy",
                    "lastName": "Eckersall",
                    "email": "ceckersall1m@wisc.edu",
                    "phoneNumber": "8095576419"
                }, {
                    "id": 60,
                    "firstName": "Letisha",
                    "lastName": "Blankau",
                    "email": "lblankau1n@wiley.com",
                    "phoneNumber": "6996993358"
                }, {
                    "id": 61,
                    "firstName": "Nani",
                    "lastName": "Lewsley",
                    "email": "nlewsley1o@amazonaws.com",
                    "phoneNumber": "6019607339"
                }, {
                    "id": 62,
                    "firstName": "Elayne",
                    "lastName": "Vorley",
                    "email": "evorley1p@cisco.com",
                    "phoneNumber": "4527792112"
                }, {
                    "id": 63,
                    "firstName": "Chrysler",
                    "lastName": "Lambrechts",
                    "email": "clambrechts1q@shutterfly.com",
                    "phoneNumber": "7284194768"
                }, {
                    "id": 64,
                    "firstName": "Maynard",
                    "lastName": "Couve",
                    "email": "mcouve1r@edublogs.org",
                    "phoneNumber": "9117083215"
                }, {
                    "id": 65,
                    "firstName": "Ida",
                    "lastName": "McInally",
                    "email": "imcinally1s@seesaa.net",
                    "phoneNumber": "5201516979"
                }, {
                    "id": 66,
                    "firstName": "Kaylyn",
                    "lastName": "Mathis",
                    "email": "kmathis1t@un.org",
                    "phoneNumber": "3213344274"
                }, {
                    "id": 67,
                    "firstName": "Petey",
                    "lastName": "Allsup",
                    "email": "pallsup1u@google.cn",
                    "phoneNumber": "8328168964"
                }, {
                    "id": 68,
                    "firstName": "Leticia",
                    "lastName": "Classen",
                    "email": "lclassen1v@umich.edu",
                    "phoneNumber": "8196085491"
                }, {
                    "id": 69,
                    "firstName": "Web",
                    "lastName": "Kilty",
                    "email": "wkilty1w@1688.com",
                    "phoneNumber": "8608255423"
                }, {
                    "id": 70,
                    "firstName": "Ruttger",
                    "lastName": "Frediani",
                    "email": "rfrediani1x@livejournal.com",
                    "phoneNumber": "4378534596"
                }, {
                    "id": 71,
                    "firstName": "Neille",
                    "lastName": "Lighton",
                    "email": "nlighton1y@apache.org",
                    "phoneNumber": "5204414539"
                }, {
                    "id": 72,
                    "firstName": "Arri",
                    "lastName": "Landal",
                    "email": "alandal1z@go.com",
                    "phoneNumber": "8776218954"
                }, {
                    "id": 73,
                    "firstName": "Marieann",
                    "lastName": "Orteaux",
                    "email": "morteaux20@meetup.com",
                    "phoneNumber": "7627721182"
                }, {
                    "id": 74,
                    "firstName": "Martita",
                    "lastName": "Gutans",
                    "email": "mgutans21@reuters.com",
                    "phoneNumber": "9939724671"
                }, {
                    "id": 75,
                    "firstName": "Coreen",
                    "lastName": "Healings",
                    "email": "chealings22@vk.com",
                    "phoneNumber": "5679049974"
                }, {
                    "id": 76,
                    "firstName": "Shannon",
                    "lastName": "Luttgert",
                    "email": "sluttgert23@storify.com",
                    "phoneNumber": "1874349741"
                }, {
                    "id": 77,
                    "firstName": "Tedd",
                    "lastName": "Breheny",
                    "email": "tbreheny24@trellian.com",
                    "phoneNumber": "2389612206"
                }, {
                    "id": 78,
                    "firstName": "Tersina",
                    "lastName": "Top",
                    "email": "ttop25@blinklist.com",
                    "phoneNumber": "6757101578"
                }, {
                    "id": 79,
                    "firstName": "Myrtia",
                    "lastName": "Reece",
                    "email": "mreece26@admin.ch",
                    "phoneNumber": "4944431199"
                }, {
                    "id": 80,
                    "firstName": "Karalee",
                    "lastName": "Rodie",
                    "email": "krodie27@sina.com.cn",
                    "phoneNumber": "6189984446"
                }, {
                    "id": 81,
                    "firstName": "Shepperd",
                    "lastName": "Tipperton",
                    "email": "stipperton28@t-online.de",
                    "phoneNumber": "2561014102"
                }, {
                    "id": 82,
                    "firstName": "Walliw",
                    "lastName": "Sketh",
                    "email": "wsketh29@wikipedia.org",
                    "phoneNumber": "6169327459"
                }, {
                    "id": 83,
                    "firstName": "Basia",
                    "lastName": "Spadollini",
                    "email": "bspadollini2a@desdev.cn",
                    "phoneNumber": "7453067738"
                }, {
                    "id": 84,
                    "firstName": "Ernaline",
                    "lastName": "Petris",
                    "email": "epetris2b@tinypic.com",
                    "phoneNumber": "3258040540"
                }, {
                    "id": 85,
                    "firstName": "Rem",
                    "lastName": "Farrant",
                    "email": "rfarrant2c@imageshack.us",
                    "phoneNumber": "1083970387"
                }, {
                    "id": 86,
                    "firstName": "Vyky",
                    "lastName": "Kuzma",
                    "email": "vkuzma2d@hostgator.com",
                    "phoneNumber": "7064835862"
                }, {
                    "id": 87,
                    "firstName": "Giorgia",
                    "lastName": "Culbert",
                    "email": "gculbert2e@constantcontact.com",
                    "phoneNumber": "5829561403"
                }, {
                    "id": 88,
                    "firstName": "Yankee",
                    "lastName": "Rahill",
                    "email": "yrahill2f@usa.gov",
                    "phoneNumber": "9572403482"
                }, {
                    "id": 89,
                    "firstName": "Hermina",
                    "lastName": "Abrahamian",
                    "email": "habrahamian2g@mlb.com",
                    "phoneNumber": "6115712974"
                }, {
                    "id": 90,
                    "firstName": "Vina",
                    "lastName": "Stowell",
                    "email": "vstowell2h@feedburner.com",
                    "phoneNumber": "9663230619"
                }, {
                    "id": 91,
                    "firstName": "Clemmie",
                    "lastName": "Pues",
                    "email": "cpues2i@quantcast.com",
                    "phoneNumber": "9987629740"
                }, {
                    "id": 92,
                    "firstName": "Roxana",
                    "lastName": "Thackray",
                    "email": "rthackray2j@tuttocitta.it",
                    "phoneNumber": "8902146815"
                }, {
                    "id": 93,
                    "firstName": "Ardath",
                    "lastName": "Ganiclef",
                    "email": "aganiclef2k@apple.com",
                    "phoneNumber": "4836049329"
                }, {
                    "id": 94,
                    "firstName": "Opal",
                    "lastName": "McComas",
                    "email": "omccomas2l@constantcontact.com",
                    "phoneNumber": "4045220962"
                }, {
                    "id": 95,
                    "firstName": "Druci",
                    "lastName": "Crowley",
                    "email": "dcrowley2m@reuters.com",
                    "phoneNumber": "5536218395"
                }, {
                    "id": 96,
                    "firstName": "Asher",
                    "lastName": "Renzo",
                    "email": "arenzo2n@com.com",
                    "phoneNumber": "5373750090"
                }, {
                    "id": 97,
                    "firstName": "Heather",
                    "lastName": "Gayne",
                    "email": "hgayne2o@ca.gov",
                    "phoneNumber": "8699184878"
                }, {
                    "id": 98,
                    "firstName": "Humbert",
                    "lastName": "Mitcham",
                    "email": "hmitcham2p@issuu.com",
                    "phoneNumber": "6167509114"
                }, {
                    "id": 99,
                    "firstName": "Kassia",
                    "lastName": "Wait",
                    "email": "kwait2q@uiuc.edu",
                    "phoneNumber": "5821121720"
                }, {
                    "id": 100,
                    "firstName": "Hugh",
                    "lastName": "Byles",
                    "email": "hbyles2r@unicef.org",
                    "phoneNumber": "7235441980"
                }])
            } else {
                return owners;
            }
        })
        .then( owners => {
            allOwners = owners;
            return Vehicle.findAll();
        })
        .then( vehicles => {
            if( !vehicles || vehicles.length === 0 ) {
                return Vehicle.bulkCreate([{
                    "id": 1,
                    "vin": "WDDHF2EB3CA724146",
                    "make": "Dodge",
                    "model": "Avenger",
                    "firstRegistrationDate": "1994-03-20",
                    "engineCapacity": 1028
                }, {
                    "id": 2,
                    "vin": "WBAUC73508V792199",
                    "make": "Mitsubishi",
                    "model": "Eclipse",
                    "firstRegistrationDate": "1967-02-14",
                    "engineCapacity": 3536
                }, {
                    "id": 3,
                    "vin": "5FNYF3H41EB460593",
                    "make": "Saab",
                    "model": "9-5",
                    "firstRegistrationDate": "1997-08-12",
                    "engineCapacity": 5197
                }, {
                    "id": 4,
                    "vin": "1G6DC5EG2A0969170",
                    "make": "Lincoln",
                    "model": "Continental",
                    "firstRegistrationDate": "1999-04-18",
                    "engineCapacity": 10938
                }, {
                    "id": 5,
                    "vin": "SCBLF34FX4C519088",
                    "make": "Hummer",
                    "model": "H2",
                    "firstRegistrationDate": "1972-11-06",
                    "engineCapacity": 10504
                }, {
                    "id": 6,
                    "vin": "KNDPB3A21D7902129",
                    "make": "GMC",
                    "model": "1500",
                    "firstRegistrationDate": "2005-02-21",
                    "engineCapacity": 14908
                }, {
                    "id": 7,
                    "vin": "1G6DJ5EV6A0905458",
                    "make": "Mercury",
                    "model": "Milan",
                    "firstRegistrationDate": "1964-10-09",
                    "engineCapacity": 9721
                }, {
                    "id": 8,
                    "vin": "WA1WMAFP2EA073410",
                    "make": "Lincoln",
                    "model": "MKX",
                    "firstRegistrationDate": "2012-05-06",
                    "engineCapacity": 11639
                }, {
                    "id": 9,
                    "vin": "1G6DH8E51C0392605",
                    "make": "Oldsmobile",
                    "model": "Silhouette",
                    "firstRegistrationDate": "1972-08-03",
                    "engineCapacity": 3384
                }, {
                    "id": 10,
                    "vin": "5NPET4AC9AH310164",
                    "make": "Tesla",
                    "model": "Roadster",
                    "firstRegistrationDate": "2016-02-28",
                    "engineCapacity": 9329
                }, {
                    "id": 11,
                    "vin": "WA1MMAFE6AD422289",
                    "make": "Nissan",
                    "model": "GT-R",
                    "firstRegistrationDate": "1991-02-24",
                    "engineCapacity": 14446
                }, {
                    "id": 12,
                    "vin": "1FMCU0C75CK727744",
                    "make": "Hyundai",
                    "model": "Sonata",
                    "firstRegistrationDate": "2001-06-28",
                    "engineCapacity": 13064
                }, {
                    "id": 13,
                    "vin": "WBALW3C50FC351984",
                    "make": "Toyota",
                    "model": "Highlander Hybrid",
                    "firstRegistrationDate": "1967-05-02",
                    "engineCapacity": 9153
                }, {
                    "id": 14,
                    "vin": "5NPE24AF0FH342070",
                    "make": "Volkswagen",
                    "model": "GTI",
                    "firstRegistrationDate": "1961-08-13",
                    "engineCapacity": 15832
                }, {
                    "id": 15,
                    "vin": "WP1AE2A29DL704750",
                    "make": "Ford",
                    "model": "F450",
                    "firstRegistrationDate": "1987-03-25",
                    "engineCapacity": 14751
                }, {
                    "id": 16,
                    "vin": "5TDDK3DC7ES927549",
                    "make": "Cadillac",
                    "model": "XLR-V",
                    "firstRegistrationDate": "1973-05-26",
                    "engineCapacity": 5050
                }, {
                    "id": 17,
                    "vin": "1D7RB1GP3BS420312",
                    "make": "Cadillac",
                    "model": "SRX",
                    "firstRegistrationDate": "2006-11-13",
                    "engineCapacity": 4620
                }, {
                    "id": 18,
                    "vin": "WAUBC48H66K819607",
                    "make": "Volvo",
                    "model": "940",
                    "firstRegistrationDate": "2004-04-12",
                    "engineCapacity": 7159
                }, {
                    "id": 19,
                    "vin": "WBAVT13536A163266",
                    "make": "Toyota",
                    "model": "Yaris",
                    "firstRegistrationDate": "1991-06-14",
                    "engineCapacity": 863
                }, {
                    "id": 20,
                    "vin": "WAU4FBFL8BA364870",
                    "make": "Pontiac",
                    "model": "GTO",
                    "firstRegistrationDate": "1974-01-18",
                    "engineCapacity": 13780
                }, {
                    "id": 21,
                    "vin": "1C4SDJCT7CC116565",
                    "make": "Buick",
                    "model": "Rendezvous",
                    "firstRegistrationDate": "2016-02-22",
                    "engineCapacity": 12492
                }, {
                    "id": 22,
                    "vin": "1D7CW3GK7AS525900",
                    "make": "Chevrolet",
                    "model": "Prizm",
                    "firstRegistrationDate": "1967-06-21",
                    "engineCapacity": 11610
                }, {
                    "id": 23,
                    "vin": "JTDJTUD31DD056891",
                    "make": "Mercedes-Benz",
                    "model": "W201",
                    "firstRegistrationDate": "1968-08-28",
                    "engineCapacity": 12886
                }, {
                    "id": 24,
                    "vin": "KNDPB3A27B7935262",
                    "make": "Nissan",
                    "model": "Pathfinder Armada",
                    "firstRegistrationDate": "1979-04-25",
                    "engineCapacity": 1426
                }, {
                    "id": 25,
                    "vin": "WBA3N9C57EK856169",
                    "make": "Honda",
                    "model": "S2000",
                    "firstRegistrationDate": "2007-02-09",
                    "engineCapacity": 14238
                }, {
                    "id": 26,
                    "vin": "2G4WF551041807079",
                    "make": "Ram",
                    "model": "2500",
                    "firstRegistrationDate": "1998-03-31",
                    "engineCapacity": 9850
                }, {
                    "id": 27,
                    "vin": "1C3CDWDA4CD742586",
                    "make": "Mercedes-Benz",
                    "model": "W201",
                    "firstRegistrationDate": "2003-08-16",
                    "engineCapacity": 6111
                }, {
                    "id": 28,
                    "vin": "JM1DE1HY9B0060073",
                    "make": "Chevrolet",
                    "model": "Express 2500",
                    "firstRegistrationDate": "1964-03-25",
                    "engineCapacity": 4584
                }, {
                    "id": 29,
                    "vin": "WAUBFAFL5CN639543",
                    "make": "Audi",
                    "model": "Quattro",
                    "firstRegistrationDate": "1971-03-11",
                    "engineCapacity": 15426
                }, {
                    "id": 30,
                    "vin": "1N6BF0KM8FN644054",
                    "make": "Ford",
                    "model": "Mustang",
                    "firstRegistrationDate": "2011-09-04",
                    "engineCapacity": 6834
                }, {
                    "id": 31,
                    "vin": "1FMJK1F54BE792210",
                    "make": "Ford",
                    "model": "GT500",
                    "firstRegistrationDate": "1988-07-14",
                    "engineCapacity": 12571
                }, {
                    "id": 32,
                    "vin": "1N4AB7AP7DN410960",
                    "make": "GMC",
                    "model": "Yukon",
                    "firstRegistrationDate": "2015-07-18",
                    "engineCapacity": 6788
                }, {
                    "id": 33,
                    "vin": "1G6AP5SX5E0914892",
                    "make": "Mitsubishi",
                    "model": "Montero",
                    "firstRegistrationDate": "1975-08-14",
                    "engineCapacity": 3231
                }, {
                    "id": 34,
                    "vin": "2G61W5S85E9793993",
                    "make": "Volkswagen",
                    "model": "Cabriolet",
                    "firstRegistrationDate": "2015-07-15",
                    "engineCapacity": 5876
                }, {
                    "id": 35,
                    "vin": "WAUHGAFC8DN399039",
                    "make": "Ford",
                    "model": "Laser",
                    "firstRegistrationDate": "1960-11-03",
                    "engineCapacity": 7926
                }, {
                    "id": 36,
                    "vin": "KNAFX6A85F5332490",
                    "make": "Mercury",
                    "model": "Cougar",
                    "firstRegistrationDate": "2009-10-08",
                    "engineCapacity": 15468
                }, {
                    "id": 37,
                    "vin": "WBAVC73578K550211",
                    "make": "Chevrolet",
                    "model": "Astro",
                    "firstRegistrationDate": "1963-06-11",
                    "engineCapacity": 4672
                }, {
                    "id": 38,
                    "vin": "3D7JV1EP5AG234509",
                    "make": "Toyota",
                    "model": "Previa",
                    "firstRegistrationDate": "1992-04-24",
                    "engineCapacity": 6626
                }, {
                    "id": 39,
                    "vin": "1D4RE3GG6BC173443",
                    "make": "GMC",
                    "model": "2500",
                    "firstRegistrationDate": "1985-02-06",
                    "engineCapacity": 8902
                }, {
                    "id": 40,
                    "vin": "1G6YV36A575303250",
                    "make": "Chrysler",
                    "model": "200",
                    "firstRegistrationDate": "1991-09-04",
                    "engineCapacity": 11164
                }, {
                    "id": 41,
                    "vin": "WAUVC58E92A391654",
                    "make": "Ford",
                    "model": "Thunderbird",
                    "firstRegistrationDate": "1983-07-20",
                    "engineCapacity": 3961
                }, {
                    "id": 42,
                    "vin": "JA4AP3AU9CZ502793",
                    "make": "Mercedes-Benz",
                    "model": "SLK-Class",
                    "firstRegistrationDate": "2019-03-24",
                    "engineCapacity": 12889
                }, {
                    "id": 43,
                    "vin": "2T1KE4EE9AC045340",
                    "make": "Nissan",
                    "model": "Altima",
                    "firstRegistrationDate": "1964-07-28",
                    "engineCapacity": 12646
                }, {
                    "id": 44,
                    "vin": "5NPEB4AC4CH951793",
                    "make": "Pontiac",
                    "model": "Tempest",
                    "firstRegistrationDate": "1976-04-01",
                    "engineCapacity": 7572
                }, {
                    "id": 45,
                    "vin": "YV4952CF2E1697934",
                    "make": "Isuzu",
                    "model": "Rodeo",
                    "firstRegistrationDate": "1972-09-19",
                    "engineCapacity": 15265
                }, {
                    "id": 46,
                    "vin": "WBAVB73507K157183",
                    "make": "Saab",
                    "model": "9-5",
                    "firstRegistrationDate": "1962-06-22",
                    "engineCapacity": 12016
                }, {
                    "id": 47,
                    "vin": "WBAEH13587C027822",
                    "make": "Maserati",
                    "model": "Quattroporte",
                    "firstRegistrationDate": "1977-01-16",
                    "engineCapacity": 16513
                }, {
                    "id": 48,
                    "vin": "5LMJJ3J59DE735901",
                    "make": "Chevrolet",
                    "model": "Suburban",
                    "firstRegistrationDate": "1989-09-02",
                    "engineCapacity": 15127
                }, {
                    "id": 49,
                    "vin": "SALGS2DF7DA925659",
                    "make": "Acura",
                    "model": "TSX",
                    "firstRegistrationDate": "1970-06-16",
                    "engineCapacity": 7256
                }, {
                    "id": 50,
                    "vin": "WBSBR93484P605729",
                    "make": "Oldsmobile",
                    "model": "Aurora",
                    "firstRegistrationDate": "1967-12-14",
                    "engineCapacity": 13003
                }, {
                    "id": 51,
                    "vin": "JN8AE2KP2B9412256",
                    "make": "Kia",
                    "model": "Sephia",
                    "firstRegistrationDate": "1977-04-24",
                    "engineCapacity": 10268
                }, {
                    "id": 52,
                    "vin": "5N1BA0ND7FN551065",
                    "make": "BMW",
                    "model": "3 Series",
                    "firstRegistrationDate": "2012-12-10",
                    "engineCapacity": 15300
                }, {
                    "id": 53,
                    "vin": "WAUMR44E75N180394",
                    "make": "Volkswagen",
                    "model": "Touareg",
                    "firstRegistrationDate": "1978-09-07",
                    "engineCapacity": 7326
                }, {
                    "id": 54,
                    "vin": "1G4HP52K34U293574",
                    "make": "Toyota",
                    "model": "Paseo",
                    "firstRegistrationDate": "2014-10-01",
                    "engineCapacity": 2492
                }, {
                    "id": 55,
                    "vin": "WA1DGAFP4EA207008",
                    "make": "GMC",
                    "model": "Sierra 1500",
                    "firstRegistrationDate": "1993-02-12",
                    "engineCapacity": 8963
                }, {
                    "id": 56,
                    "vin": "1N6AA0EC8EN879727",
                    "make": "Pontiac",
                    "model": "Bonneville",
                    "firstRegistrationDate": "1981-08-13",
                    "engineCapacity": 2838
                }, {
                    "id": 57,
                    "vin": "TRUDD38J791768124",
                    "make": "Honda",
                    "model": "Accord",
                    "firstRegistrationDate": "1973-10-20",
                    "engineCapacity": 13186
                }, {
                    "id": 58,
                    "vin": "KMHEC4A49EA914069",
                    "make": "Nissan",
                    "model": "200SX",
                    "firstRegistrationDate": "1996-01-25",
                    "engineCapacity": 11788
                }, {
                    "id": 59,
                    "vin": "1FTMF1EW0AF464145",
                    "make": "Jeep",
                    "model": "Patriot",
                    "firstRegistrationDate": "2010-10-29",
                    "engineCapacity": 2318
                }, {
                    "id": 60,
                    "vin": "WAUDFAFL4EN658905",
                    "make": "GMC",
                    "model": "Vandura 2500",
                    "firstRegistrationDate": "1984-04-23",
                    "engineCapacity": 3725
                }, {
                    "id": 61,
                    "vin": "2C3CDZFJ0FH115034",
                    "make": "Volvo",
                    "model": "C70",
                    "firstRegistrationDate": "2016-08-24",
                    "engineCapacity": 4378
                }, {
                    "id": 62,
                    "vin": "5TFBW5F18BX049123",
                    "make": "Geo",
                    "model": "Prizm",
                    "firstRegistrationDate": "1971-04-22",
                    "engineCapacity": 9495
                }, {
                    "id": 63,
                    "vin": "JHMZE2H77ES284677",
                    "make": "Audi",
                    "model": "S5",
                    "firstRegistrationDate": "1980-11-26",
                    "engineCapacity": 3519
                }, {
                    "id": 64,
                    "vin": "1NXBE4EEXAZ358511",
                    "make": "Bentley",
                    "model": "Continental GTC",
                    "firstRegistrationDate": "1960-09-18",
                    "engineCapacity": 5300
                }, {
                    "id": 65,
                    "vin": "1N6AA0CC9CN181448",
                    "make": "Subaru",
                    "model": "SVX",
                    "firstRegistrationDate": "1990-07-28",
                    "engineCapacity": 8886
                }, {
                    "id": 66,
                    "vin": "WDDJK7DA0FF440760",
                    "make": "Dodge",
                    "model": "Nitro",
                    "firstRegistrationDate": "1986-01-03",
                    "engineCapacity": 5588
                }, {
                    "id": 67,
                    "vin": "1FMJK1G50BE166331",
                    "make": "Mercedes-Benz",
                    "model": "CLS-Class",
                    "firstRegistrationDate": "1980-12-29",
                    "engineCapacity": 2767
                }, {
                    "id": 68,
                    "vin": "2G4GT5GX5E9221687",
                    "make": "Hyundai",
                    "model": "Azera",
                    "firstRegistrationDate": "1995-07-02",
                    "engineCapacity": 9701
                }, {
                    "id": 69,
                    "vin": "WAUVC58E75A404213",
                    "make": "Chevrolet",
                    "model": "2500",
                    "firstRegistrationDate": "1985-03-03",
                    "engineCapacity": 2743
                }, {
                    "id": 70,
                    "vin": "SAJWA4DC7FM904949",
                    "make": "GMC",
                    "model": "Sierra 1500",
                    "firstRegistrationDate": "1964-07-22",
                    "engineCapacity": 11649
                }, {
                    "id": 71,
                    "vin": "3C4PDCBB9ET399259",
                    "make": "Dodge",
                    "model": "Ram 3500",
                    "firstRegistrationDate": "2012-03-20",
                    "engineCapacity": 15005
                }, {
                    "id": 72,
                    "vin": "1G6DC5E53C0456737",
                    "make": "Porsche",
                    "model": "911",
                    "firstRegistrationDate": "1980-03-27",
                    "engineCapacity": 1229
                }, {
                    "id": 73,
                    "vin": "JH4KB16527C688201",
                    "make": "Saab",
                    "model": "9000",
                    "firstRegistrationDate": "1999-02-28",
                    "engineCapacity": 2267
                }, {
                    "id": 74,
                    "vin": "WBAKF5C54BE568766",
                    "make": "GMC",
                    "model": "Sierra Hybrid",
                    "firstRegistrationDate": "1998-08-02",
                    "engineCapacity": 7351
                }, {
                    "id": 75,
                    "vin": "1FTEW1CM1EF917894",
                    "make": "Chevrolet",
                    "model": "2500",
                    "firstRegistrationDate": "1966-10-21",
                    "engineCapacity": 13840
                }, {
                    "id": 76,
                    "vin": "WAUTFAFH4BN969687",
                    "make": "Chevrolet",
                    "model": "Sportvan G30",
                    "firstRegistrationDate": "1970-05-15",
                    "engineCapacity": 14494
                }, {
                    "id": 77,
                    "vin": "5TDDCRFH1ES461562",
                    "make": "Acura",
                    "model": "Integra",
                    "firstRegistrationDate": "1987-07-16",
                    "engineCapacity": 1078
                }, {
                    "id": 78,
                    "vin": "WBAVB73597F053560",
                    "make": "GMC",
                    "model": "Yukon",
                    "firstRegistrationDate": "1992-06-23",
                    "engineCapacity": 13268
                }, {
                    "id": 79,
                    "vin": "4USBU53506L619443",
                    "make": "Dodge",
                    "model": "Ram 3500",
                    "firstRegistrationDate": "2009-01-03",
                    "engineCapacity": 6044
                }, {
                    "id": 80,
                    "vin": "1G6AE5SX7F0038849",
                    "make": "Suzuki",
                    "model": "Grand Vitara",
                    "firstRegistrationDate": "2009-03-18",
                    "engineCapacity": 5243
                }, {
                    "id": 81,
                    "vin": "5GADT13S542683658",
                    "make": "Bugatti",
                    "model": "Veyron",
                    "firstRegistrationDate": "1986-12-22",
                    "engineCapacity": 16794
                }, {
                    "id": 82,
                    "vin": "WBAPM5C5XBA436551",
                    "make": "Audi",
                    "model": "Coupe Quattro",
                    "firstRegistrationDate": "2005-07-31",
                    "engineCapacity": 6699
                }, {
                    "id": 83,
                    "vin": "JN8AZ1MUXCW287463",
                    "make": "Daewoo",
                    "model": "Leganza",
                    "firstRegistrationDate": "1981-11-13",
                    "engineCapacity": 7926
                }, {
                    "id": 84,
                    "vin": "WBA3B9C52EJ485873",
                    "make": "Geo",
                    "model": "Prizm",
                    "firstRegistrationDate": "1962-10-31",
                    "engineCapacity": 12392
                }, {
                    "id": 85,
                    "vin": "WAUUL78E38A092063",
                    "make": "Dodge",
                    "model": "Challenger",
                    "firstRegistrationDate": "2006-05-24",
                    "engineCapacity": 5901
                }, {
                    "id": 86,
                    "vin": "3VW4A7ATXDM094548",
                    "make": "Dodge",
                    "model": "Dynasty",
                    "firstRegistrationDate": "2019-12-16",
                    "engineCapacity": 11702
                }, {
                    "id": 87,
                    "vin": "WAUFFAFL7FN737771",
                    "make": "Lincoln",
                    "model": "Continental",
                    "firstRegistrationDate": "2002-04-29",
                    "engineCapacity": 2693
                }, {
                    "id": 88,
                    "vin": "TRUSC28N041054285",
                    "make": "Chevrolet",
                    "model": "Camaro",
                    "firstRegistrationDate": "1970-09-17",
                    "engineCapacity": 8225
                }, {
                    "id": 89,
                    "vin": "WBABD33484J362961",
                    "make": "Dodge",
                    "model": "Dakota Club",
                    "firstRegistrationDate": "2008-10-02",
                    "engineCapacity": 6756
                }, {
                    "id": 90,
                    "vin": "WAURD68DX2A113857",
                    "make": "Mercedes-Benz",
                    "model": "CL-Class",
                    "firstRegistrationDate": "2016-12-05",
                    "engineCapacity": 12818
                }, {
                    "id": 91,
                    "vin": "WBAUL7C50AV492846",
                    "make": "Chevrolet",
                    "model": "Corvette",
                    "firstRegistrationDate": "2005-09-04",
                    "engineCapacity": 14065
                }, {
                    "id": 92,
                    "vin": "5FRYD4H6XFB867096",
                    "make": "Nissan",
                    "model": "Maxima",
                    "firstRegistrationDate": "1997-06-30",
                    "engineCapacity": 15580
                }, {
                    "id": 93,
                    "vin": "3VW4A7AT7DM578032",
                    "make": "Mazda",
                    "model": "RX-8",
                    "firstRegistrationDate": "2009-03-08",
                    "engineCapacity": 6520
                }, {
                    "id": 94,
                    "vin": "WAUPL68E94A001945",
                    "make": "Honda",
                    "model": "FCX Clarity",
                    "firstRegistrationDate": "1961-08-30",
                    "engineCapacity": 13024
                }, {
                    "id": 95,
                    "vin": "1FTSW3A54AE141206",
                    "make": "Honda",
                    "model": "Accord",
                    "firstRegistrationDate": "1967-02-22",
                    "engineCapacity": 5684
                }, {
                    "id": 96,
                    "vin": "4T1BF1FK2EU036760",
                    "make": "GMC",
                    "model": "Envoy XL",
                    "firstRegistrationDate": "2008-11-01",
                    "engineCapacity": 3439
                }, {
                    "id": 97,
                    "vin": "WAUKG74F36N307974",
                    "make": "Mercury",
                    "model": "Grand Marquis",
                    "firstRegistrationDate": "1976-03-07",
                    "engineCapacity": 12123
                }, {
                    "id": 98,
                    "vin": "WBABN33453J623782",
                    "make": "Acura",
                    "model": "RL",
                    "firstRegistrationDate": "1978-03-09",
                    "engineCapacity": 6546
                }, {
                    "id": 99,
                    "vin": "JN1AJ0HP4AM146238",
                    "make": "GMC",
                    "model": "Yukon Denali",
                    "firstRegistrationDate": "2001-10-24",
                    "engineCapacity": 16596
                }, {
                    "id": 100,
                    "vin": "WA1EY94L58D558450",
                    "make": "Chevrolet",
                    "model": "Camaro",
                    "firstRegistrationDate": "1964-06-12",
                    "engineCapacity": 8955
                }])
                    .then( () => {
                        return Owner.findAll();
                    });
            } else {
                return vehicles;
            }
        })
        .then( vehicles => {
            allVehicles = vehicles;
            return OwnerVehicle.findAll();
        })
        .then( registration => {
            if( !registration || registration.length === 0 ) {
            //     for(let i=0; i<300; i++)
            //     {
            //         let dateFrom=faker.date.between('1960-01-01',new Date());
            //         let dateTo = new Date();
            //         dateTo.setDate(dateFrom+Math.random()*30000);
            //
            //         registrations[i]={dateFrom:dateFrom
            //             ,dateTo:dateTo<=new Date()?dateTo:null
            //             ,registrationNumber: faker.regexpStyleStringParse('[A-Z]{2,3} \\d{4,5}')
            //             ,insuranceNumber: faker.regexpStyleStringParse('\\d{9}')
            //             ,owner_id: faker.numberBetween(0,100)
            //             ,vehicle_id: faker.numberBetween(0,100)};
            //     }
                return OwnerVehicle.bulkCreate([{
                    "id": 1,
                    "dateFrom": "1965-09-30",
                    "dateTo": "2007-06-17",
                    "registrationNumber": "POP 5793",
                    "insuranceNumber": "561674060",
                    "owner_id": 83,
                    "vehicle_id": 33
                }, {
                    "id": 2,
                    "dateFrom": "1971-05-20",
                    "dateTo": "1977-12-23",
                    "registrationNumber": "PI 3512",
                    "insuranceNumber": "744075984",
                    "owner_id": 36,
                    "vehicle_id": 21
                }, {
                    "id": 3,
                    "dateFrom": "1981-06-15",
                    "dateTo": "2009-07-10",
                    "registrationNumber": "IF 95028",
                    "insuranceNumber": "275415841",
                    "owner_id": 80,
                    "vehicle_id": 86
                }, {
                    "id": 4,
                    "dateFrom": "2001-04-17",
                    "dateTo": "2003-11-10",
                    "registrationNumber": "CS 8409",
                    "insuranceNumber": "517115683",
                    "owner_id": 35,
                    "vehicle_id": 78
                }, {
                    "id": 5,
                    "dateFrom": "1980-06-06",
                    "dateTo": "2000-06-18",
                    "registrationNumber": "THE 5847",
                    "insuranceNumber": "625687190",
                    "owner_id": 97,
                    "vehicle_id": 42
                }, {
                    "id": 6,
                    "dateFrom": "1976-10-07",
                    "dateTo": "2006-11-05",
                    "registrationNumber": "CS 12949",
                    "insuranceNumber": "662932677",
                    "owner_id": 90,
                    "vehicle_id": 44
                }, {
                    "id": 7,
                    "dateFrom": "1972-10-16",
                    "dateTo": "2020-03-17",
                    "registrationNumber": "ES 44722",
                    "insuranceNumber": "012837911",
                    "owner_id": 44,
                    "vehicle_id": 99
                }, {
                    "id": 8,
                    "dateFrom": "1981-04-12",
                    "dateTo": "2004-12-03",
                    "registrationNumber": "HA 07809",
                    "insuranceNumber": "245093711",
                    "owner_id": 91,
                    "vehicle_id": 66
                }, {
                    "id": 9,
                    "dateFrom": "1991-10-15",
                    "dateTo": "2015-10-03",
                    "registrationNumber": "PEW 17643",
                    "insuranceNumber": "547837007",
                    "owner_id": 89,
                    "vehicle_id": 28
                }, {
                    "id": 10,
                    "dateFrom": "1980-03-08",
                    "dateTo": "2015-04-30",
                    "registrationNumber": "JAW 00344",
                    "insuranceNumber": "695179236",
                    "owner_id": 50,
                    "vehicle_id": 57
                }, {
                    "id": 11,
                    "dateFrom": "2015-05-22",
                    "dateTo": null,
                    "registrationNumber": "IT KQ1C",
                    "insuranceNumber": "441928140",
                    "owner_id": 43,
                    "vehicle_id": 33
                }, {
                    "id": 12,
                    "dateFrom": "2013-09-27",
                    "dateTo": null,
                    "registrationNumber": "TO 69F2K",
                    "insuranceNumber": "427592878",
                    "owner_id": 25,
                    "vehicle_id": 27
                }, {
                    "id": 13,
                    "dateFrom": "2000-05-01",
                    "dateTo": null,
                    "registrationNumber": "PAL R6W9",
                    "insuranceNumber": "595884839",
                    "owner_id": 73,
                    "vehicle_id": 45
                }, {
                    "id": 14,
                    "dateFrom": "1993-11-23",
                    "dateTo": null,
                    "registrationNumber": "COD C16S",
                    "insuranceNumber": "477043217",
                    "owner_id": 26,
                    "vehicle_id": 92
                }, {
                    "id": 15,
                    "dateFrom": "2000-08-16",
                    "dateTo": null,
                    "registrationNumber": "ME 0XLK",
                    "insuranceNumber": "760470820",
                    "owner_id": 88,
                    "vehicle_id": 26
                }, {
                    "id": 16,
                    "dateFrom": "1991-08-09",
                    "dateTo": null,
                    "registrationNumber": "AY ITD5",
                    "insuranceNumber": "386773756",
                    "owner_id": 53,
                    "vehicle_id": 48
                }, {
                    "id": 17,
                    "dateFrom": "2009-02-19",
                    "dateTo": null,
                    "registrationNumber": "PA 9TML",
                    "insuranceNumber": "478660489",
                    "owner_id": 16,
                    "vehicle_id": 71
                }, {
                    "id": 18,
                    "dateFrom": "1996-11-04",
                    "dateTo": null,
                    "registrationNumber": "MUM 7F5T",
                    "insuranceNumber": "504452902",
                    "owner_id": 76,
                    "vehicle_id": 96
                }, {
                    "id": 19,
                    "dateFrom": "2013-06-25",
                    "dateTo": null,
                    "registrationNumber": "OK Z4B0",
                    "insuranceNumber": "941279156",
                    "owner_id": 89,
                    "vehicle_id": 92
                }, {
                    "id": 20,
                    "dateFrom": "2009-02-26",
                    "dateTo": null,
                    "registrationNumber": "PAP 055A",
                    "insuranceNumber": "333851234",
                    "owner_id": 15,
                    "vehicle_id": 76
                }, {
                    "id": 21,
                    "dateFrom": "2019-06-07",
                    "dateTo": null,
                    "registrationNumber": "RAP NYO1",
                    "insuranceNumber": "719112015",
                    "owner_id": 12,
                    "vehicle_id": 88
                }, {
                    "id": 22,
                    "dateFrom": "2008-06-18",
                    "dateTo": null,
                    "registrationNumber": "ALE RI8G",
                    "insuranceNumber": "736100375",
                    "owner_id": 84,
                    "vehicle_id": 3
                }, {
                    "id": 23,
                    "dateFrom": "2013-08-30",
                    "dateTo": null,
                    "registrationNumber": "CS 9N7H",
                    "insuranceNumber": "744382796",
                    "owner_id": 67,
                    "vehicle_id": 9
                }, {
                    "id": 24,
                    "dateFrom": "2006-01-25",
                    "dateTo": null,
                    "registrationNumber": "UP 96OK",
                    "insuranceNumber": "105721445",
                    "owner_id": 89,
                    "vehicle_id": 66
                }, {
                    "id": 25,
                    "dateFrom": "2011-04-07",
                    "dateTo": null,
                    "registrationNumber": "WAY SP1D",
                    "insuranceNumber": "706642307",
                    "owner_id": 11,
                    "vehicle_id": 28
                }, {
                    "id": 26,
                    "dateFrom": "1991-06-16",
                    "dateTo": null,
                    "registrationNumber": "MU 59IQP",
                    "insuranceNumber": "941159036",
                    "owner_id": 49,
                    "vehicle_id": 23
                }, {
                    "id": 27,
                    "dateFrom": "2014-04-22",
                    "dateTo": null,
                    "registrationNumber": "EH 40P9K",
                    "insuranceNumber": "125796235",
                    "owner_id": 26,
                    "vehicle_id": 26
                }, {
                    "id": 28,
                    "dateFrom": "2017-10-03",
                    "dateTo": null,
                    "registrationNumber": "AS 09FNO",
                    "insuranceNumber": "429251617",
                    "owner_id": 73,
                    "vehicle_id": 35
                }, {
                    "id": 29,
                    "dateFrom": "2017-05-20",
                    "dateTo": null,
                    "registrationNumber": "FRO 10T8",
                    "insuranceNumber": "117686642",
                    "owner_id": 23,
                    "vehicle_id": 81
                }, {
                    "id": 30,
                    "dateFrom": "2005-03-14",
                    "dateTo": null,
                    "registrationNumber": "AN EB5Q0",
                    "insuranceNumber": "622856052",
                    "owner_id": 85,
                    "vehicle_id": 93
                }, {
                    "id": 31,
                    "dateFrom": "2002-09-06",
                    "dateTo": null,
                    "registrationNumber": "PEW 5965R",
                    "insuranceNumber": "139128481",
                    "owner_id": 63,
                    "vehicle_id": 41
                }, {
                    "id": 32,
                    "dateFrom": "2006-04-19",
                    "dateTo": null,
                    "registrationNumber": "US XHYV6",
                    "insuranceNumber": "105573963",
                    "owner_id": 52,
                    "vehicle_id": 100
                }, {
                    "id": 33,
                    "dateFrom": "2014-11-28",
                    "dateTo": null,
                    "registrationNumber": "NO 1IW5",
                    "insuranceNumber": "910015305",
                    "owner_id": 22,
                    "vehicle_id": 55
                }, {
                    "id": 34,
                    "dateFrom": "1999-10-12",
                    "dateTo": null,
                    "registrationNumber": "BAY W118",
                    "insuranceNumber": "320411938",
                    "owner_id": 45,
                    "vehicle_id": 13
                }, {
                    "id": 35,
                    "dateFrom": "2001-12-04",
                    "dateTo": null,
                    "registrationNumber": "OF UFU6",
                    "insuranceNumber": "809114017",
                    "owner_id": 33,
                    "vehicle_id": 3
                }, {
                    "id": 36,
                    "dateFrom": "1996-07-04",
                    "dateTo": null,
                    "registrationNumber": "DO G44I",
                    "insuranceNumber": "084321499",
                    "owner_id": 63,
                    "vehicle_id": 10
                }, {
                    "id": 37,
                    "dateFrom": "1990-02-22",
                    "dateTo": null,
                    "registrationNumber": "CS U6DO",
                    "insuranceNumber": "532233890",
                    "owner_id": 56,
                    "vehicle_id": 43
                }, {
                    "id": 38,
                    "dateFrom": "1997-11-28",
                    "dateTo": null,
                    "registrationNumber": "IN 6V36",
                    "insuranceNumber": "563839964",
                    "owner_id": 4,
                    "vehicle_id": 95
                }, {
                    "id": 39,
                    "dateFrom": "2009-12-01",
                    "dateTo": null,
                    "registrationNumber": "COD JYEDW",
                    "insuranceNumber": "268650187",
                    "owner_id": 34,
                    "vehicle_id": 31
                }, {
                    "id": 40,
                    "dateFrom": "2018-02-17",
                    "dateTo": null,
                    "registrationNumber": "TOE 2G773",
                    "insuranceNumber": "681075029",
                    "owner_id": 73,
                    "vehicle_id": 33
                }, {
                    "id": 41,
                    "dateFrom": "2014-05-26",
                    "dateTo": null,
                    "registrationNumber": "ACE B4C2",
                    "insuranceNumber": "999986725",
                    "owner_id": 5,
                    "vehicle_id": 21
                }, {
                    "id": 42,
                    "dateFrom": "2011-11-14",
                    "dateTo": null,
                    "registrationNumber": "SHE F2WN",
                    "insuranceNumber": "165037639",
                    "owner_id": 64,
                    "vehicle_id": 3
                }, {
                    "id": 43,
                    "dateFrom": "1990-07-27",
                    "dateTo": null,
                    "registrationNumber": "RAN D949P",
                    "insuranceNumber": "023245537",
                    "owner_id": 19,
                    "vehicle_id": 92
                }, {
                    "id": 44,
                    "dateFrom": "2010-04-03",
                    "dateTo": null,
                    "registrationNumber": "FOX Q03D8",
                    "insuranceNumber": "436082999",
                    "owner_id": 59,
                    "vehicle_id": 26
                }, {
                    "id": 45,
                    "dateFrom": "2020-04-19",
                    "dateTo": null,
                    "registrationNumber": "CAR Q6Y57",
                    "insuranceNumber": "802154977",
                    "owner_id": 45,
                    "vehicle_id": 82
                }, {
                    "id": 46,
                    "dateFrom": "2009-05-18",
                    "dateTo": null,
                    "registrationNumber": "LOT 2KNP",
                    "insuranceNumber": "648150098",
                    "owner_id": 55,
                    "vehicle_id": 60
                }, {
                    "id": 47,
                    "dateFrom": "2014-02-27",
                    "dateTo": null,
                    "registrationNumber": "SAW JXC45",
                    "insuranceNumber": "762467721",
                    "owner_id": 30,
                    "vehicle_id": 64
                }, {
                    "id": 48,
                    "dateFrom": "1991-05-10",
                    "dateTo": null,
                    "registrationNumber": "EH RUX8",
                    "insuranceNumber": "681143773",
                    "owner_id": 62,
                    "vehicle_id": 93
                }, {
                    "id": 49,
                    "dateFrom": "2014-01-11",
                    "dateTo": null,
                    "registrationNumber": "OWN Q9Y9",
                    "insuranceNumber": "250162368",
                    "owner_id": 31,
                    "vehicle_id": 27
                }, {
                    "id": 50,
                    "dateFrom": "1990-02-22",
                    "dateTo": null,
                    "registrationNumber": "AIM T8YHG",
                    "insuranceNumber": "550934825",
                    "owner_id": 22,
                    "vehicle_id": 55
                }, {
                    "id": 51,
                    "dateFrom": "2015-05-11",
                    "dateTo": null,
                    "registrationNumber": "NON 8R7W",
                    "insuranceNumber": "335124832",
                    "owner_id": 7,
                    "vehicle_id": 3
                }, {
                    "id": 52,
                    "dateFrom": "2000-08-03",
                    "dateTo": null,
                    "registrationNumber": "MS 7Z0OA",
                    "insuranceNumber": "683762071",
                    "owner_id": 12,
                    "vehicle_id": 15
                }, {
                    "id": 53,
                    "dateFrom": "2017-01-25",
                    "dateTo": null,
                    "registrationNumber": "AD 38716",
                    "insuranceNumber": "606476528",
                    "owner_id": 57,
                    "vehicle_id": 13
                }, {
                    "id": 54,
                    "dateFrom": "2006-06-30",
                    "dateTo": null,
                    "registrationNumber": "AN 3UK2",
                    "insuranceNumber": "366761986",
                    "owner_id": 60,
                    "vehicle_id": 94
                }, {
                    "id": 55,
                    "dateFrom": "1997-01-30",
                    "dateTo": null,
                    "registrationNumber": "WIN 8DRN2",
                    "insuranceNumber": "672202143",
                    "owner_id": 92,
                    "vehicle_id": 42
                }, {
                    "id": 56,
                    "dateFrom": "2018-12-11",
                    "dateTo": null,
                    "registrationNumber": "AIR AUX0",
                    "insuranceNumber": "520945214",
                    "owner_id": 65,
                    "vehicle_id": 59
                }, {
                    "id": 57,
                    "dateFrom": "2012-12-30",
                    "dateTo": null,
                    "registrationNumber": "AD PAQG",
                    "insuranceNumber": "341381323",
                    "owner_id": 45,
                    "vehicle_id": 33
                }, {
                    "id": 58,
                    "dateFrom": "1999-07-14",
                    "dateTo": null,
                    "registrationNumber": "VAN 7X4J",
                    "insuranceNumber": "480260000",
                    "owner_id": 59,
                    "vehicle_id": 65
                }, {
                    "id": 59,
                    "dateFrom": "2000-07-18",
                    "dateTo": null,
                    "registrationNumber": "BE 18786",
                    "insuranceNumber": "908850188",
                    "owner_id": 94,
                    "vehicle_id": 73
                }, {
                    "id": 60,
                    "dateFrom": "2008-08-24",
                    "dateTo": null,
                    "registrationNumber": "US 3639L",
                    "insuranceNumber": "994066117",
                    "owner_id": 80,
                    "vehicle_id": 34
                }]);
            } else {
                return registration;
            }
        })
        .then( () => {
            return Announcement.findAll();
        })
        .then(announcement => {
            if( !announcement || announcement.length === 0 ) {
                return Announcement.bulkCreate([
                    {dateOfPublication: new Date(),expirationDate: '2021-05-05',text:'Przypominamy, że z powodu obecnej sytuacji epidemiologicznej obsługa interesantów odbywa się wyłącznie telefonicznie lub mailowo.'},
                    {dateOfPublication: new Date(),expirationDate: '2021-05-05',text:'W związku z epidemią czas na rejestrację pojazdu zostaje wydłużony z 30 do 180 dni.'},
                ])
                    .then( () => {
                        return Announcement.findAll();
                    });
            } else {
                return announcement;
            }
        });
};